/*!
* \file   StationaryHeatTransfer.cxx
* \brief  this file implements the StationaryHeatTransfer Behaviour.
*         File generated by tfel version 3.4.0-dev
* \author Thomas Helfer
* \date   15 / 02 / 2019
 */

#include<string>
#include<cstring>
#include<sstream>
#include<fstream>
#include<stdexcept>

#include"TFEL/Raise.hxx"
#include"TFEL/Material/StationaryHeatTransferBehaviourData.hxx"
#include"TFEL/Material/StationaryHeatTransferIntegrationData.hxx"
#include"TFEL/Material/StationaryHeatTransfer.hxx"

namespace tfel{

namespace material{

StationaryHeatTransferParametersInitializer&
StationaryHeatTransferParametersInitializer::get()
{
static StationaryHeatTransferParametersInitializer i;
return i;
}

StationaryHeatTransferParametersInitializer::StationaryHeatTransferParametersInitializer()
{
this->A = 0.0375;
this->B = 0.0002165;
this->minimal_time_step_scaling_factor = 0.1;
this->maximal_time_step_scaling_factor = 1.79769e+308;
// Reading parameters from a file
StationaryHeatTransferParametersInitializer::readParameters(*this,"StationaryHeatTransfer-parameters.txt");
}

void
StationaryHeatTransferParametersInitializer::set(const char* const key,
const double v){
using namespace std;
if(::strcmp("A",key)==0){
this->A = v;
} else if(::strcmp("B",key)==0){
this->B = v;
} else if(::strcmp("minimal_time_step_scaling_factor",key)==0){
this->minimal_time_step_scaling_factor = v;
} else if(::strcmp("maximal_time_step_scaling_factor",key)==0){
this->maximal_time_step_scaling_factor = v;
} else {
tfel::raise("StationaryHeatTransferParametersInitializer::set: "
" no parameter named '"+std::string(key)+"'");
}
}

double
StationaryHeatTransferParametersInitializer::getDouble(const std::string& n,
const std::string& v)
{
double value;
std::istringstream converter(v);
converter >> value;
tfel::raise_if(!converter||(!converter.eof()),
"StationaryHeatTransferParametersInitializer::getDouble: "
"can't convert '"+v+"' to double for parameter '"+ n+"'");
return value;
}

void
StationaryHeatTransferParametersInitializer::readParameters(StationaryHeatTransferParametersInitializer& pi,const char* const fn){
auto tokenize = [](const std::string& line){
std::istringstream tokenizer(line);
std::vector<std::string> tokens;
std::copy(std::istream_iterator<std::string>(tokenizer),
std::istream_iterator<std::string>(),
std::back_inserter(tokens));
return tokens;
};
std::ifstream f(fn);
if(!f){
return;
}
size_t ln = 1u;
while(!f.eof()){
auto line = std::string{};
std::getline(f,line);
auto tokens = tokenize(line);
auto throw_if = [ln,line,fn](const bool c,const std::string& m){
tfel::raise_if(c,"StationaryHeatTransferParametersInitializer::readParameters: "
"error at line '"+std::to_string(ln)+"' "
"while reading parameter file '"+std::string(fn)+"'"
"("+m+")");
};
if(tokens.empty()){
continue;
}
if(tokens[0][0]=='#'){
continue;
}
throw_if(tokens.size()!=2u,"invalid number of tokens");
if("A"==tokens[0]){
pi.A = StationaryHeatTransferParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("B"==tokens[0]){
pi.B = StationaryHeatTransferParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("minimal_time_step_scaling_factor"==tokens[0]){
pi.minimal_time_step_scaling_factor = StationaryHeatTransferParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("maximal_time_step_scaling_factor"==tokens[0]){
pi.maximal_time_step_scaling_factor = StationaryHeatTransferParametersInitializer::getDouble(tokens[0],tokens[1]);
} else {
throw_if(true,"invalid parameter '"+tokens[0]+"'");
}
}
}

} // end of namespace material

} // end of namespace tfel

