# This files gather compiler flags that are common to g++, clang and
# pathCC

mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wall" "W" "Wshadow")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wpointer-arith" "Wcast-qual" "Wcast-align")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wwrite-strings" "Wctor-dtor-privacy" "Wnon-virtual-dtor")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Woverloaded-virtual" "Wreturn-type" "Wfloat-equal")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wno-endif-labels" "Wmissing-format-attribute")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wno-multichar" "Wno-deprecated-declarations" "Wpacked")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wredundant-decls")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wunknown-pragmas" "Wundef" "Wreorder")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wno-conversion")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wdouble-promotion")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Winit-self")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wlogical-op")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wmissing-include-dirs")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wnoexcept")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wold-style-cast")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wstrict-null-sentinel")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wtrampolines")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wvector-operation-performance")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wignored-qualifiers")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsequence-point")
# mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsuggest-attribute=pure")
# mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsuggest-attribute=const")
# mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsuggest-attribute=noreturn")
# mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsuggest-attribute=format")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wswitch-bool")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wlogical-not-parentheses")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsizeof-array-argument")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wbool-compare")
# mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Winline")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wshift-negative-value")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wshift-overflow")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wtautological-compare")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wnull-dereference")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wduplicated-cond")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wmisleading-indentation")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wduplicated-branches")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wregister")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wint-in-bool-context")
mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsuggest-override")

if(enable-developer-warnings)
  mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wextra")
  mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "pedantic")
  mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsign-compare")
  mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wswitch")
  mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wmissing-declarations")
  mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wzero-as-null-pointer-constant")
  mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsign-conversion")
  mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsign-promo")
  if(NOT (WIN32 AND ( CMAKE_SIZEOF_VOID_P EQUAL 8 )))
    mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wlong-long")
  endif(NOT (WIN32 AND ( CMAKE_SIZEOF_VOID_P EQUAL 8 )))
else(enable-developer-warnings)
  mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wno-switch-enum")
  mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wno-covered-switch-default")
  mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wno-covered-switch-default")
  mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wno-sign-compare")
  mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wno-missing-declarations")
  mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wno-weak-vtables")
  mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wno-unused-macros")
endif(enable-developer-warnings)


if(enable-advanced-developer-warnings)
  mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsuggest-final-types")
  mgis_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsuggest-final-methods")
endif(enable-advanced-developer-warnings)
